// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAlumnosSeg;

#nullable disable

namespace WebApiAlumnosSeg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220422015020_Fecha_Creacion")]
    partial class Fecha_Creacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.AlumnoClase", b =>
                {
                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId", "ClaseId");

                    b.HasIndex("ClaseId");

                    b.ToTable("AlumnoClase");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Cursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.AlumnoClase", b =>
                {
                    b.HasOne("WebApiAlumnosSeg.Entidades.Alumno", "Alumno")
                        .WithMany("AlumnoClase")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiAlumnosSeg.Entidades.Clase", "Clase")
                        .WithMany("AlumnoClase")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Cursos", b =>
                {
                    b.HasOne("WebApiAlumnosSeg.Entidades.Clase", "Clase")
                        .WithMany("Cursos")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Alumno", b =>
                {
                    b.Navigation("AlumnoClase");
                });

            modelBuilder.Entity("WebApiAlumnosSeg.Entidades.Clase", b =>
                {
                    b.Navigation("AlumnoClase");

                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
